name: sarkiapp
description: Turkish Song Association MVP
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  provider: ^6.0.5
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/words/word_list_tr.json

